In [3]:
import numpy as np 
a_arr = np.array([[1, 2], [4, -1]])
b_arr = np.array([[-3, 2], [-4, 1]])
c = b_arr.dot(a_arr) + a_arr.dot(b_arr) 
print(c)

[[-6 -4]
 [-8 -2]]


In [4]:
import numpy as np 
arr = np.array([[-1, 2], [0, 1],])
power= np.dot(arr,arr)
print(power) 


[[1 0]
 [0 1]]


In [5]:
matrix_1 = np.array([[3, 5], [6, -1]])
matrix_2 = np.array([[2, 1], [-3, 2]])
matrix_3 = matrix_1.dot(matrix_2)
print(matrix_3)


[[-9 13]
 [15  4]]


In [6]:
import numpy as np 
arr_a = np.array([[2, 3, 4], [1, 0, 6], [7, 8, 9]])
a_det = np.linalg.det(arr_a)
print(format(a_det,'.9g'))


35


In [10]:
import numpy as np 
a_arr = np.array([[1, 2, 3,4], [-2, 1, -4, 3], [3,-4,-1, 2,], [4, 3, -2, -1]])
a_det = np.linalg.det(a_arr)
print(format(a_det,'.9g'))


900


In [11]:
a = np.array([[2, 5, 7], [6, 3, 4], [5, -2, -3]])
a_inv = np.linalg.inv(a) 
print(a_inv)


[[  1.  -1.   1.]
 [-38.  41. -34.]
 [ 27. -29.  24.]]


In [12]:
aa = np.array([[1, -1, 3,4], [0, -1, 2, 1], [1, 1, -1, 2], [2, 3, -5, 3]])
rank = np.linalg.matrix_rank(aa) 
print(rank) 

3


In [13]:
A = np.matrix('3 -5 3; 1 2 1; 2 7 -1')
B = np.matrix('1; 4; 8')
print('A=', A)
print('B=',B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
print('X=',X)


A= [[ 3 -5  3]
 [ 1  2  1]
 [ 2  7 -1]]
B= [[1]
 [4]
 [8]]
[[ 0.27272727 -0.48484848  0.33333333]
 [-0.09090909  0.27272727  0.        ]
 [-0.09090909  0.93939394 -0.33333333]]
X= [[1.]
 [1.]
 [1.]]


In [14]:
a = np.matrix('3 -5 3; 1 2 1; 2 7 -1') 
b = np.matrix('1; 4; 8') 
def kram(a,b): 
    det_a = np.linalg.det(a) 
    if det_a != 0: 
       a1 = np.matrix(a) 
       a2 = np.matrix(a) 
       a3 = np.matrix(a) 
       a1[:, 0] = b 
       a2[:, 1] = b 
       a3[:, 2] = b 
       x = np.linalg.det(a1)/det_a 
       y =np.linalg.det(a2)/det_a 
       z= np.linalg.det(a3)/det_a 
       print('Solving a system of linear algebraic equations by Cramer*s method') 
       print('x=',x.round(3),'y=',y.round(3),'z=',z.round(3))  
    else: 
        print('Determinant equals zero, the system has no solutions') 
    return x,y,z 
kram(a,b) 
print('Checking the correctness of the solution\n', np.linalg.solve(a,b).round(3))


Solving a system of linear algebraic equations by Cramer*s method
x= 1.0 y= 1.0 z= 1.0
Checking the correctness of the solution
 [[1.]
 [1.]
 [1.]]


In [15]:
a = np.array(np.random.randint(0,5, size=(3,4)))
average_rows = np.mean(a, axis=1)
minimum = np.min(average_rows)
print(a)
print(average_rows)

print('Найнижче середнє значення:', minimum)


[[0 0 0 3]
 [1 0 4 1]
 [3 2 3 0]]
[0.75 1.5  2.  ]
Найнижче середнє значення: 0.75
